<?php
/**
 * @file
 * tiffin_content.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function tiffin_content_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: menu-about-tu_accommodations--restaurants:node/47.
  $menu_links['menu-about-tu_accommodations--restaurants:node/47'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/47',
    'router_path' => 'node/%',
    'link_title' => 'Accommodations & Restaurants',
    'options' => array(
      'identifier' => 'menu-about-tu_accommodations--restaurants:node/47',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 5,
    'customized' => 0,
    'uuid' => '63ad4e29-7291-461c-a20a-4076caa0bc01',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
    'parent_identifier' => 'menu-about-tu_commencement:node/22',
  );
  // Exported menu link: menu-about-tu_accommodations:node/30.
  $menu_links['menu-about-tu_accommodations:node/30'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/30',
    'router_path' => 'node/%',
    'link_title' => 'Accommodations',
    'options' => array(
      'identifier' => 'menu-about-tu_accommodations:node/30',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => 'f8ea4cb6-3d15-4e3c-8006-1f96f4e85933',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
    'parent_identifier' => 'menu-about-tu_visiting-tiffin-oh:node/17',
  );
  // Exported menu link: menu-about-tu_accreditations:node/23.
  $menu_links['menu-about-tu_accreditations:node/23'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/23',
    'router_path' => 'node/%',
    'link_title' => 'Accreditations',
    'options' => array(
      'identifier' => 'menu-about-tu_accreditations:node/23',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => 'd03e2b26-dd77-4f23-83bc-39069da0fd10',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
    'parent_identifier' => 'menu-about-tu_tu-at-a-glance:node/14',
  );
  // Exported menu link: menu-about-tu_area-attractions:node/31.
  $menu_links['menu-about-tu_area-attractions:node/31'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/31',
    'router_path' => 'node/%',
    'link_title' => 'Area Attractions',
    'options' => array(
      'identifier' => 'menu-about-tu_area-attractions:node/31',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 1,
    'customized' => 0,
    'uuid' => 'a82995c6-aac4-4f5b-b0cf-e1e1917aa883',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
    'parent_identifier' => 'menu-about-tu_visiting-tiffin-oh:node/17',
  );
  // Exported menu link: menu-about-tu_benefits:node/33.
  $menu_links['menu-about-tu_benefits:node/33'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/33',
    'router_path' => 'node/%',
    'link_title' => 'Benefits',
    'options' => array(
      'identifier' => 'menu-about-tu_benefits:node/33',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 1,
    'customized' => 0,
    'uuid' => '88191c4c-ebbe-4f8b-9468-801b037acd9e',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
    'parent_identifier' => 'menu-about-tu_employment:node/20',
  );
  // Exported menu link: menu-about-tu_commencement:node/22.
  $menu_links['menu-about-tu_commencement:node/22'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/22',
    'router_path' => 'node/%',
    'link_title' => 'Commencement',
    'options' => array(
      'identifier' => 'menu-about-tu_commencement:node/22',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => 10,
    'customized' => 0,
    'uuid' => '31aade4d-a825-4b65-9e0a-67a28dd72a38',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
  );
  // Exported menu link: menu-about-tu_disability-services:node/39.
  $menu_links['menu-about-tu_disability-services:node/39'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/39',
    'router_path' => 'node/%',
    'link_title' => 'Disability Services',
    'options' => array(
      'identifier' => 'menu-about-tu_disability-services:node/39',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 5,
    'customized' => 0,
    'uuid' => 'd42719eb-d8ec-4a47-a15e-6ac79dfd6ba4',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
    'parent_identifier' => 'menu-about-tu_institutional-diversity:node/21',
  );
  // Exported menu link: menu-about-tu_diversity-committee:node/35.
  $menu_links['menu-about-tu_diversity-committee:node/35'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/35',
    'router_path' => 'node/%',
    'link_title' => 'Diversity Committee',
    'options' => array(
      'identifier' => 'menu-about-tu_diversity-committee:node/35',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 1,
    'customized' => 0,
    'uuid' => '28049a6c-60ae-48dc-8ba3-9b6f05b97bde',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
    'parent_identifier' => 'menu-about-tu_institutional-diversity:node/21',
  );
  // Exported menu link: menu-about-tu_diversity-organizations:node/37.
  $menu_links['menu-about-tu_diversity-organizations:node/37'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/37',
    'router_path' => 'node/%',
    'link_title' => 'Diversity Organizations',
    'options' => array(
      'identifier' => 'menu-about-tu_diversity-organizations:node/37',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 3,
    'customized' => 0,
    'uuid' => '3ce5877a-a126-487f-bc56-dd7b166ace0d',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
    'parent_identifier' => 'menu-about-tu_institutional-diversity:node/21',
  );
  // Exported menu link: menu-about-tu_diversity-scholarships:node/38.
  $menu_links['menu-about-tu_diversity-scholarships:node/38'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/38',
    'router_path' => 'node/%',
    'link_title' => 'Diversity Scholarships',
    'options' => array(
      'identifier' => 'menu-about-tu_diversity-scholarships:node/38',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 4,
    'customized' => 0,
    'uuid' => 'f19564a7-4b12-4517-b758-4585bf90214a',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
    'parent_identifier' => 'menu-about-tu_institutional-diversity:node/21',
  );
  // Exported menu link: menu-about-tu_employment:node/20.
  $menu_links['menu-about-tu_employment:node/20'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/20',
    'router_path' => 'node/%',
    'link_title' => 'Employment',
    'options' => array(
      'identifier' => 'menu-about-tu_employment:node/20',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => 8,
    'customized' => 0,
    'uuid' => 'ecad4e1d-dfeb-4da1-b66d-96ec3cbd5864',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
  );
  // Exported menu link: menu-about-tu_faqs:node/25.
  $menu_links['menu-about-tu_faqs:node/25'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/25',
    'router_path' => 'node/%',
    'link_title' => 'FAQ\'s',
    'options' => array(
      'identifier' => 'menu-about-tu_faqs:node/25',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 2,
    'customized' => 0,
    'uuid' => '1ceb6864-c9e7-4a6f-9800-d6ccb92914d5',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
    'parent_identifier' => 'menu-about-tu_tu-at-a-glance:node/14',
  );
  // Exported menu link: menu-about-tu_fast-facts:node/24.
  $menu_links['menu-about-tu_fast-facts:node/24'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/24',
    'router_path' => 'node/%',
    'link_title' => 'Fast Facts',
    'options' => array(
      'identifier' => 'menu-about-tu_fast-facts:node/24',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 1,
    'customized' => 0,
    'uuid' => '647cf0d4-798f-4e93-adc4-80fb1fd43ce7',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
    'parent_identifier' => 'menu-about-tu_tu-at-a-glance:node/14',
  );
  // Exported menu link: menu-about-tu_graduation-apparel--accessories:node/44.
  $menu_links['menu-about-tu_graduation-apparel--accessories:node/44'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/44',
    'router_path' => 'node/%',
    'link_title' => 'Graduation Apparel & Accessories',
    'options' => array(
      'identifier' => 'menu-about-tu_graduation-apparel--accessories:node/44',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 2,
    'customized' => 0,
    'uuid' => '7379985c-1707-4948-b41b-c95be85a098d',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
    'parent_identifier' => 'menu-about-tu_commencement:node/22',
  );
  // Exported menu link: menu-about-tu_graduation-application:node/48.
  $menu_links['menu-about-tu_graduation-application:node/48'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/48',
    'router_path' => 'node/%',
    'link_title' => 'Graduation Application',
    'options' => array(
      'identifier' => 'menu-about-tu_graduation-application:node/48',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 6,
    'customized' => 0,
    'uuid' => 'ecee5c2e-3ab4-4a61-beb3-82f9ebd01428',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
    'parent_identifier' => 'menu-about-tu_commencement:node/22',
  );
  // Exported menu link: menu-about-tu_graduation-checklist:node/43.
  $menu_links['menu-about-tu_graduation-checklist:node/43'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/43',
    'router_path' => 'node/%',
    'link_title' => 'Graduation Checklist',
    'options' => array(
      'identifier' => 'menu-about-tu_graduation-checklist:node/43',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 1,
    'customized' => 0,
    'uuid' => 'a51de1ea-0180-438d-813b-6eb766fd7a93',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
    'parent_identifier' => 'menu-about-tu_commencement:node/22',
  );
  // Exported menu link: menu-about-tu_history:node/26.
  $menu_links['menu-about-tu_history:node/26'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/26',
    'router_path' => 'node/%',
    'link_title' => 'History',
    'options' => array(
      'identifier' => 'menu-about-tu_history:node/26',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 3,
    'customized' => 0,
    'uuid' => '19a17a0e-6654-4091-826d-7b669754d729',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
    'parent_identifier' => 'menu-about-tu_tu-at-a-glance:node/14',
  );
  // Exported menu link: menu-about-tu_host-an-event:http://eventscheduling.tiffin.edu/virtualems/.
  $menu_links['menu-about-tu_host-an-event:http://eventscheduling.tiffin.edu/virtualems/'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'http://eventscheduling.tiffin.edu/virtualems/',
    'router_path' => '',
    'link_title' => 'Host An Event',
    'options' => array(
      'identifier' => 'menu-about-tu_host-an-event:http://eventscheduling.tiffin.edu/virtualems/',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 7,
    'customized' => 0,
    'uuid' => '2e475a96-88ee-409b-a425-93187ecb461e',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
  );
  // Exported menu link: menu-about-tu_institutional-diversity:node/21.
  $menu_links['menu-about-tu_institutional-diversity:node/21'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/21',
    'router_path' => 'node/%',
    'link_title' => 'Institutional Diversity',
    'options' => array(
      'identifier' => 'menu-about-tu_institutional-diversity:node/21',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => 9,
    'customized' => 0,
    'uuid' => 'c53ad8d6-28c5-49cf-bb7f-3f5d49a4ab4f',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
  );
  // Exported menu link: menu-about-tu_institutional-research:node/27.
  $menu_links['menu-about-tu_institutional-research:node/27'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/27',
    'router_path' => 'node/%',
    'link_title' => 'Institutional Research',
    'options' => array(
      'identifier' => 'menu-about-tu_institutional-research:node/27',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 4,
    'customized' => 0,
    'uuid' => '1f2c52d1-f91d-4be7-813d-1254ca2cd1b0',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
    'parent_identifier' => 'menu-about-tu_tu-at-a-glance:node/14',
  );
  // Exported menu link: menu-about-tu_job-listings:node/32.
  $menu_links['menu-about-tu_job-listings:node/32'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/32',
    'router_path' => 'node/%',
    'link_title' => 'Job Listings',
    'options' => array(
      'identifier' => 'menu-about-tu_job-listings:node/32',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => 'c6bacfec-22d0-4f09-ad92-5403ce8e7cdd',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
    'parent_identifier' => 'menu-about-tu_employment:node/20',
  );
  // Exported menu link: menu-about-tu_location-parking--seating:node/42.
  $menu_links['menu-about-tu_location-parking--seating:node/42'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/42',
    'router_path' => 'node/%',
    'link_title' => 'Location, Parking & Seating',
    'options' => array(
      'identifier' => 'menu-about-tu_location-parking--seating:node/42',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => '481f1397-0f63-478a-ab32-5d4e58a57320',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
    'parent_identifier' => 'menu-about-tu_commencement:node/22',
  );
  // Exported menu link: menu-about-tu_maps--directions:node/16.
  $menu_links['menu-about-tu_maps--directions:node/16'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/16',
    'router_path' => 'node/%',
    'link_title' => 'Maps & Directions',
    'options' => array(
      'identifier' => 'menu-about-tu_maps--directions:node/16',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 3,
    'customized' => 0,
    'uuid' => '9d34bfb8-a456-4f1e-a9e4-a9c46cdbc3d6',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
  );
  // Exported menu link: menu-about-tu_meet-our-faculty:node/18.
  $menu_links['menu-about-tu_meet-our-faculty:node/18'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/18',
    'router_path' => 'node/%',
    'link_title' => 'Meet Our Faculty',
    'options' => array(
      'identifier' => 'menu-about-tu_meet-our-faculty:node/18',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 5,
    'customized' => 0,
    'uuid' => '01cb8055-83f3-40fa-bbd3-c2f1805f08af',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
  );
  // Exported menu link: menu-about-tu_mission:node/28.
  $menu_links['menu-about-tu_mission:node/28'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/28',
    'router_path' => 'node/%',
    'link_title' => 'Mission',
    'options' => array(
      'identifier' => 'menu-about-tu_mission:node/28',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 5,
    'customized' => 0,
    'uuid' => '9c63443d-fea4-4b50-8d5f-c30b8ffd486f',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
    'parent_identifier' => 'menu-about-tu_tu-at-a-glance:node/14',
  );
  // Exported menu link: menu-about-tu_news--events:node/19.
  $menu_links['menu-about-tu_news--events:node/19'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/19',
    'router_path' => 'node/%',
    'link_title' => 'News & Events',
    'options' => array(
      'identifier' => 'menu-about-tu_news--events:node/19',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 6,
    'customized' => 0,
    'uuid' => '8ae471dd-00c8-44c8-bf95-3c64e494937a',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
  );
  // Exported menu link: menu-about-tu_our-campuses:node/15.
  $menu_links['menu-about-tu_our-campuses:node/15'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/15',
    'router_path' => 'node/%',
    'link_title' => 'Our Campuses',
    'options' => array(
      'identifier' => 'menu-about-tu_our-campuses:node/15',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 2,
    'customized' => 0,
    'uuid' => '1ac3c2da-1989-4567-a5ea-76e68016c1a4',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
  );
  // Exported menu link: menu-about-tu_photography:node/45.
  $menu_links['menu-about-tu_photography:node/45'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/45',
    'router_path' => 'node/%',
    'link_title' => 'Photography',
    'options' => array(
      'identifier' => 'menu-about-tu_photography:node/45',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 3,
    'customized' => 0,
    'uuid' => 'a7c99b1e-f0a5-4f43-87a3-984fae5443f5',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
    'parent_identifier' => 'menu-about-tu_commencement:node/22',
  );
  // Exported menu link: menu-about-tu_presidents-welcome:node/13.
  $menu_links['menu-about-tu_presidents-welcome:node/13'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/13',
    'router_path' => 'node/%',
    'link_title' => 'President\'s Welcome',
    'options' => array(
      'identifier' => 'menu-about-tu_presidents-welcome:node/13',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => '4301046d-ecbd-41a2-b6df-2db77bb741ee',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
  );
  // Exported menu link: menu-about-tu_resources:node/41.
  $menu_links['menu-about-tu_resources:node/41'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/41',
    'router_path' => 'node/%',
    'link_title' => 'Resources',
    'options' => array(
      'identifier' => 'menu-about-tu_resources:node/41',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 7,
    'customized' => 0,
    'uuid' => '410e15ea-6128-4a35-878b-e536740d22e0',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
    'parent_identifier' => 'menu-about-tu_institutional-diversity:node/21',
  );
  // Exported menu link: menu-about-tu_safe-zone:node/40.
  $menu_links['menu-about-tu_safe-zone:node/40'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/40',
    'router_path' => 'node/%',
    'link_title' => 'Safe Zone',
    'options' => array(
      'identifier' => 'menu-about-tu_safe-zone:node/40',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 6,
    'customized' => 0,
    'uuid' => '4dbf17f4-468d-469e-b8c6-49eb3a68fa63',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
    'parent_identifier' => 'menu-about-tu_institutional-diversity:node/21',
  );
  // Exported menu link: menu-about-tu_strategic-plan:node/36.
  $menu_links['menu-about-tu_strategic-plan:node/36'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/36',
    'router_path' => 'node/%',
    'link_title' => 'Strategic Plan',
    'options' => array(
      'identifier' => 'menu-about-tu_strategic-plan:node/36',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 2,
    'customized' => 0,
    'uuid' => '91c8c6d1-5b4b-47a0-9388-934363f5be9c',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
    'parent_identifier' => 'menu-about-tu_institutional-diversity:node/21',
  );
  // Exported menu link: menu-about-tu_student-consumer-information:node/29.
  $menu_links['menu-about-tu_student-consumer-information:node/29'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/29',
    'router_path' => 'node/%',
    'link_title' => 'Student Consumer Information',
    'options' => array(
      'identifier' => 'menu-about-tu_student-consumer-information:node/29',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 6,
    'customized' => 0,
    'uuid' => 'ff2428cc-b356-445a-bd90-a5820a31d925',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
    'parent_identifier' => 'menu-about-tu_tu-at-a-glance:node/14',
  );
  // Exported menu link: menu-about-tu_title-ix:node/34.
  $menu_links['menu-about-tu_title-ix:node/34'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/34',
    'router_path' => 'node/%',
    'link_title' => 'Title IX',
    'options' => array(
      'identifier' => 'menu-about-tu_title-ix:node/34',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => '96e022f8-d45f-4727-828a-34fb83a3653a',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
    'parent_identifier' => 'menu-about-tu_institutional-diversity:node/21',
  );
  // Exported menu link: menu-about-tu_tu-at-a-glance:node/14.
  $menu_links['menu-about-tu_tu-at-a-glance:node/14'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/14',
    'router_path' => 'node/%',
    'link_title' => 'TU At A Glance',
    'options' => array(
      'identifier' => 'menu-about-tu_tu-at-a-glance:node/14',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => 1,
    'customized' => 0,
    'uuid' => '6a857216-d6bd-4ee0-b6fe-3691284254e7',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
  );
  // Exported menu link: menu-about-tu_tu-commencement-tips:node/46.
  $menu_links['menu-about-tu_tu-commencement-tips:node/46'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/46',
    'router_path' => 'node/%',
    'link_title' => 'TU Commencement Tips',
    'options' => array(
      'identifier' => 'menu-about-tu_tu-commencement-tips:node/46',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 4,
    'customized' => 0,
    'uuid' => 'b1453ea2-44b2-4c09-a056-4562dde5e766',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
    'parent_identifier' => 'menu-about-tu_commencement:node/22',
  );
  // Exported menu link: menu-about-tu_visiting-tiffin-oh:node/17.
  $menu_links['menu-about-tu_visiting-tiffin-oh:node/17'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'node/17',
    'router_path' => 'node/%',
    'link_title' => 'Visiting Tiffin, OH',
    'options' => array(
      'identifier' => 'menu-about-tu_visiting-tiffin-oh:node/17',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => 4,
    'customized' => 0,
    'uuid' => 'dd6efaf5-e696-4b22-8868-0f859579b44c',
    'language' => 'und',
    'menu_links_customized' => 0,
    'menu_links_language' => 'und',
    'menu_links_customized_2' => 0,
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Accommodations');
  t('Accommodations & Restaurants');
  t('Accreditations');
  t('Area Attractions');
  t('Benefits');
  t('Commencement');
  t('Disability Services');
  t('Diversity Committee');
  t('Diversity Organizations');
  t('Diversity Scholarships');
  t('Employment');
  t('FAQ\'s');
  t('Fast Facts');
  t('Graduation Apparel & Accessories');
  t('Graduation Application');
  t('Graduation Checklist');
  t('History');
  t('Host An Event');
  t('Institutional Diversity');
  t('Institutional Research');
  t('Job Listings');
  t('Location, Parking & Seating');
  t('Maps & Directions');
  t('Meet Our Faculty');
  t('Mission');
  t('News & Events');
  t('Our Campuses');
  t('Photography');
  t('President\'s Welcome');
  t('Resources');
  t('Safe Zone');
  t('Strategic Plan');
  t('Student Consumer Information');
  t('TU At A Glance');
  t('TU Commencement Tips');
  t('Title IX');
  t('Visiting Tiffin, OH');

  return $menu_links;
}
