<?php
/**
 * @file
 * tiffin_sidebar_menus.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function tiffin_sidebar_menus_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: menu-about-tu_commencement:home.
  $menu_links['menu-about-tu_commencement:home'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'home',
    'router_path' => 'home',
    'link_title' => 'Commencement',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-about-tu_commencement:home',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -40,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-about-tu_employment:home.
  $menu_links['menu-about-tu_employment:home'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'home',
    'router_path' => 'home',
    'link_title' => 'Employment',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-about-tu_employment:home',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-about-tu_host-an-event:home.
  $menu_links['menu-about-tu_host-an-event:home'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'home',
    'router_path' => 'home',
    'link_title' => 'Host An Event',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-about-tu_host-an-event:home',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-about-tu_institutional-diversity:home.
  $menu_links['menu-about-tu_institutional-diversity:home'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'home',
    'router_path' => 'home',
    'link_title' => 'Institutional Diversity',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-about-tu_institutional-diversity:home',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -41,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-about-tu_maps--directions:home.
  $menu_links['menu-about-tu_maps--directions:home'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'home',
    'router_path' => 'home',
    'link_title' => 'Maps & Directions',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-about-tu_maps--directions:home',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-about-tu_meet-our-faculty:home.
  $menu_links['menu-about-tu_meet-our-faculty:home'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'home',
    'router_path' => 'home',
    'link_title' => 'Meet Our Faculty',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-about-tu_meet-our-faculty:home',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-about-tu_news--events:home.
  $menu_links['menu-about-tu_news--events:home'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'home',
    'router_path' => 'home',
    'link_title' => 'News & Events',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-about-tu_news--events:home',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-about-tu_our-campuses:home.
  $menu_links['menu-about-tu_our-campuses:home'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'home',
    'router_path' => 'home',
    'link_title' => 'Our Campuses',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-about-tu_our-campuses:home',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-about-tu_presidents-welcome:home.
  $menu_links['menu-about-tu_presidents-welcome:home'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'home',
    'router_path' => 'home',
    'link_title' => 'President\'s Welcome',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-about-tu_presidents-welcome:home',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-about-tu_tu-at-a-glance:home.
  $menu_links['menu-about-tu_tu-at-a-glance:home'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'home',
    'router_path' => 'home',
    'link_title' => 'TU At a Glance',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-about-tu_tu-at-a-glance:home',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-about-tu_visiting-tiffin-oh:home.
  $menu_links['menu-about-tu_visiting-tiffin-oh:home'] = array(
    'menu_name' => 'menu-about-tu',
    'link_path' => 'home',
    'router_path' => 'home',
    'link_title' => 'Visiting Tiffin, OH',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-about-tu_visiting-tiffin-oh:home',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-academics_academic-resources:home.
  $menu_links['menu-academics_academic-resources:home'] = array(
    'menu_name' => 'menu-academics',
    'link_path' => 'home',
    'router_path' => 'home',
    'link_title' => 'Academic Resources',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-academics_academic-resources:home',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-academics_assessment:home.
  $menu_links['menu-academics_assessment:home'] = array(
    'menu_name' => 'menu-academics',
    'link_path' => 'home',
    'router_path' => 'home',
    'link_title' => 'Assessment',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-academics_assessment:home',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -39,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-academics_associate-programs:home.
  $menu_links['menu-academics_associate-programs:home'] = array(
    'menu_name' => 'menu-academics',
    'link_path' => 'home',
    'router_path' => 'home',
    'link_title' => 'Associate Programs',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-academics_associate-programs:home',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-academics_calendar--catalog:home.
  $menu_links['menu-academics_calendar--catalog:home'] = array(
    'menu_name' => 'menu-academics',
    'link_path' => 'home',
    'router_path' => 'home',
    'link_title' => 'Calendar & Catalog',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-academics_calendar--catalog:home',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -40,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-academics_china-program:home.
  $menu_links['menu-academics_china-program:home'] = array(
    'menu_name' => 'menu-academics',
    'link_path' => 'home',
    'router_path' => 'home',
    'link_title' => 'China Program',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-academics_china-program:home',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-academics_disability-services:home.
  $menu_links['menu-academics_disability-services:home'] = array(
    'menu_name' => 'menu-academics',
    'link_path' => 'home',
    'router_path' => 'home',
    'link_title' => 'Disability Services',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-academics_disability-services:home',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -38,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-academics_graduate-programs:home.
  $menu_links['menu-academics_graduate-programs:home'] = array(
    'menu_name' => 'menu-academics',
    'link_path' => 'home',
    'router_path' => 'home',
    'link_title' => 'Graduate Programs',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-academics_graduate-programs:home',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-academics_library:home.
  $menu_links['menu-academics_library:home'] = array(
    'menu_name' => 'menu-academics',
    'link_path' => 'home',
    'router_path' => 'home',
    'link_title' => 'Library',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-academics_library:home',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-academics_meet-our-faculty:home.
  $menu_links['menu-academics_meet-our-faculty:home'] = array(
    'menu_name' => 'menu-academics',
    'link_path' => 'home',
    'router_path' => 'home',
    'link_title' => 'Meet Our Faculty',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-academics_meet-our-faculty:home',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -41,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-academics_online-and-off-campus-bachelor-degree-programs:home.
  $menu_links['menu-academics_online-and-off-campus-bachelor-degree-programs:home'] = array(
    'menu_name' => 'menu-academics',
    'link_path' => 'home',
    'router_path' => 'home',
    'link_title' => 'Online and Off-Campus Bachelor Degree Programs',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-academics_online-and-off-campus-bachelor-degree-programs:home',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-academics_schools:home.
  $menu_links['menu-academics_schools:home'] = array(
    'menu_name' => 'menu-academics',
    'link_path' => 'home',
    'router_path' => 'home',
    'link_title' => 'Schools',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-academics_schools:home',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-academics_special-programs:home.
  $menu_links['menu-academics_special-programs:home'] = array(
    'menu_name' => 'menu-academics',
    'link_path' => 'home',
    'router_path' => 'home',
    'link_title' => 'Special Programs',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-academics_special-programs:home',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-academics_transcript-request:home.
  $menu_links['menu-academics_transcript-request:home'] = array(
    'menu_name' => 'menu-academics',
    'link_path' => 'home',
    'router_path' => 'home',
    'link_title' => 'Transcript Request',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-academics_transcript-request:home',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -37,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-academics_undergraduate-programs:home.
  $menu_links['menu-academics_undergraduate-programs:home'] = array(
    'menu_name' => 'menu-academics',
    'link_path' => 'home',
    'router_path' => 'home',
    'link_title' => 'Undergraduate Programs',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-academics_undergraduate-programs:home',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-admissions_apply-now:home.
  $menu_links['menu-admissions_apply-now:home'] = array(
    'menu_name' => 'menu-admissions',
    'link_path' => 'home',
    'router_path' => 'home',
    'link_title' => 'Apply Now',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-admissions_apply-now:home',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-admissions_financial-aid:home.
  $menu_links['menu-admissions_financial-aid:home'] = array(
    'menu_name' => 'menu-admissions',
    'link_path' => 'home',
    'router_path' => 'home',
    'link_title' => 'Financial Aid',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-admissions_financial-aid:home',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-admissions_graduate:home.
  $menu_links['menu-admissions_graduate:home'] = array(
    'menu_name' => 'menu-admissions',
    'link_path' => 'home',
    'router_path' => 'home',
    'link_title' => 'Graduate',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-admissions_graduate:home',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-admissions_international:home.
  $menu_links['menu-admissions_international:home'] = array(
    'menu_name' => 'menu-admissions',
    'link_path' => 'home',
    'router_path' => 'home',
    'link_title' => 'International',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-admissions_international:home',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-admissions_online-and-off-campus-bachelor-degree-programs:home.
  $menu_links['menu-admissions_online-and-off-campus-bachelor-degree-programs:home'] = array(
    'menu_name' => 'menu-admissions',
    'link_path' => 'home',
    'router_path' => 'home',
    'link_title' => 'Online and Off-Campus Bachelor Degree Programs',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-admissions_online-and-off-campus-bachelor-degree-programs:home',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-admissions_transfer:home.
  $menu_links['menu-admissions_transfer:home'] = array(
    'menu_name' => 'menu-admissions',
    'link_path' => 'home',
    'router_path' => 'home',
    'link_title' => 'Transfer',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-admissions_transfer:home',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-admissions_undergraduate:home.
  $menu_links['menu-admissions_undergraduate:home'] = array(
    'menu_name' => 'menu-admissions',
    'link_path' => 'home',
    'router_path' => 'home',
    'link_title' => 'Undergraduate',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-admissions_undergraduate:home',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-admissions_visit-tiffin-university:home.
  $menu_links['menu-admissions_visit-tiffin-university:home'] = array(
    'menu_name' => 'menu-admissions',
    'link_path' => 'home',
    'router_path' => 'home',
    'link_title' => 'Visit Tiffin University',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-admissions_visit-tiffin-university:home',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Academic Resources');
  t('Apply Now');
  t('Assessment');
  t('Associate Programs');
  t('Calendar & Catalog');
  t('China Program');
  t('Commencement');
  t('Disability Services');
  t('Employment');
  t('Financial Aid');
  t('Graduate');
  t('Graduate Programs');
  t('Host An Event');
  t('Institutional Diversity');
  t('International');
  t('Library');
  t('Maps & Directions');
  t('Meet Our Faculty');
  t('News & Events');
  t('Online and Off-Campus Bachelor Degree Programs');
  t('Our Campuses');
  t('President\'s Welcome');
  t('Schools');
  t('Special Programs');
  t('TU At a Glance');
  t('Transcript Request');
  t('Transfer');
  t('Undergraduate');
  t('Undergraduate Programs');
  t('Visit Tiffin University');
  t('Visiting Tiffin, OH');

  return $menu_links;
}
