<?php
/**
 * @file
 * tiffin_search.strongarm.inc
 */

/**
 * Implements hook_strongarm().
 */
function tiffin_search_strongarm() {
  $export = array();

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'apachesolr_attachments_entity_bundle_indexing_board_member';
  $strongarm->value = 'none';
  $export['apachesolr_attachments_entity_bundle_indexing_board_member'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'apachesolr_attachments_entity_bundle_indexing_events';
  $strongarm->value = 'none';
  $export['apachesolr_attachments_entity_bundle_indexing_events'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'apachesolr_attachments_entity_bundle_indexing_event_calendar';
  $strongarm->value = 'none';
  $export['apachesolr_attachments_entity_bundle_indexing_event_calendar'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'apachesolr_attachments_entity_bundle_indexing_faculty';
  $strongarm->value = 'seperate';
  $export['apachesolr_attachments_entity_bundle_indexing_faculty'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'apachesolr_attachments_entity_bundle_indexing_news_page';
  $strongarm->value = 'seperate';
  $export['apachesolr_attachments_entity_bundle_indexing_news_page'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'apachesolr_attachments_entity_bundle_indexing_panel';
  $strongarm->value = 'seperate';
  $export['apachesolr_attachments_entity_bundle_indexing_panel'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'apachesolr_attachments_entity_bundle_indexing_program';
  $strongarm->value = 'seperate';
  $export['apachesolr_attachments_entity_bundle_indexing_program'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'apachesolr_attachments_entity_bundle_indexing_staff';
  $strongarm->value = 'seperate';
  $export['apachesolr_attachments_entity_bundle_indexing_staff'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'apachesolr_attachments_entity_bundle_indexing_wetkit_documentation';
  $strongarm->value = 'seperate';
  $export['apachesolr_attachments_entity_bundle_indexing_wetkit_documentation'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'apachesolr_attachments_entity_bundle_indexing_wetkit_page';
  $strongarm->value = 'seperate';
  $export['apachesolr_attachments_entity_bundle_indexing_wetkit_page'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'apachesolr_attachments_excluded_extensions';
  $strongarm->value = 'aif art avi bmp gif ico jpg mov mp3 mp4 mpg oga ogv png psd ra ram rgb tif wmv';
  $export['apachesolr_attachments_excluded_extensions'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'apachesolr_attachments_extract_using';
  $strongarm->value = 'solr';
  $export['apachesolr_attachments_extract_using'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'apachesolr_attachments_filesize_limit';
  $strongarm->value = '41943040';
  $export['apachesolr_attachments_filesize_limit'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'apachesolr_attachments_tika_jar';
  $strongarm->value = '';
  $export['apachesolr_attachments_tika_jar'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'apachesolr_attachments_tika_path';
  $strongarm->value = '';
  $export['apachesolr_attachments_tika_path'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_any_force';
  $strongarm->value = 0;
  $export['custom_search_blocks_1_any_force'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_any_restricts';
  $strongarm->value = 0;
  $export['custom_search_blocks_1_any_restricts'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_criteria_negative_display';
  $strongarm->value = 0;
  $export['custom_search_blocks_1_criteria_negative_display'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_criteria_negative_label';
  $strongarm->value = 'Containing none of the words';
  $export['custom_search_blocks_1_criteria_negative_label'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_criteria_negative_region';
  $strongarm->value = 'block';
  $export['custom_search_blocks_1_criteria_negative_region'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_criteria_negative_weight';
  $strongarm->value = '-6';
  $export['custom_search_blocks_1_criteria_negative_weight'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_criteria_or_display';
  $strongarm->value = 0;
  $export['custom_search_blocks_1_criteria_or_display'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_criteria_or_label';
  $strongarm->value = 'Containing any of the words';
  $export['custom_search_blocks_1_criteria_or_label'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_criteria_or_region';
  $strongarm->value = 'block';
  $export['custom_search_blocks_1_criteria_or_region'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_criteria_or_weight';
  $strongarm->value = '-9';
  $export['custom_search_blocks_1_criteria_or_weight'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_criteria_phrase_display';
  $strongarm->value = 0;
  $export['custom_search_blocks_1_criteria_phrase_display'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_criteria_phrase_label';
  $strongarm->value = 'Containing the phrase';
  $export['custom_search_blocks_1_criteria_phrase_label'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_criteria_phrase_region';
  $strongarm->value = 'block';
  $export['custom_search_blocks_1_criteria_phrase_region'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_criteria_phrase_weight';
  $strongarm->value = '-7';
  $export['custom_search_blocks_1_criteria_phrase_weight'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_custom_paths_region';
  $strongarm->value = 'block';
  $export['custom_search_blocks_1_custom_paths_region'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_custom_paths_weight';
  $strongarm->value = '-5';
  $export['custom_search_blocks_1_custom_paths_weight'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_hint_text';
  $strongarm->value = 'Enter the terms you wish to search for.';
  $export['custom_search_blocks_1_hint_text'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_image_path';
  $strongarm->value = '';
  $export['custom_search_blocks_1_image_path'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_label';
  $strongarm->value = 'Search this site';
  $export['custom_search_blocks_1_label'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_label_visibility';
  $strongarm->value = 0;
  $export['custom_search_blocks_1_label_visibility'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_max_length';
  $strongarm->value = '150';
  $export['custom_search_blocks_1_max_length'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_node_types';
  $strongarm->value = array(
    'wetkit_page' => 'wetkit_page',
    'board_member' => 'board_member',
    'event_calendar' => 'event_calendar',
    'events' => 'events',
    'news_page' => 'news_page',
    'panel' => 'panel',
    'program' => 'program',
    'wetkit_documentation' => 0,
    'facebook' => 0,
    'faculty' => 0,
    'instagram' => 0,
    'staff' => 0,
    'testimonials_slider' => 0,
    'tweet' => 0,
    'webform' => 0,
  );
  $export['custom_search_blocks_1_node_types'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_node_types_excluded';
  $strongarm->value = array(
    'board_member' => 'board_member',
    'facebook' => 'facebook',
    'faculty' => 'faculty',
    'instagram' => 'instagram',
    'staff' => 'staff',
    'testimonials_slider' => 'testimonials_slider',
    'tweet' => 'tweet',
    'webform' => 'webform',
    'wetkit_page' => 0,
    'wetkit_documentation' => 0,
    'event_calendar' => 0,
    'events' => 0,
    'news_page' => 0,
    'panel' => 0,
    'program' => 0,
  );
  $export['custom_search_blocks_1_node_types_excluded'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_order';
  $strongarm->value = array(
    'search_box' => array(
      'sort' => '-10',
      'region' => 'block',
    ),
    'criteria_or' => array(
      'sort' => '-9',
      'region' => 'block',
    ),
    'criteria_phrase' => array(
      'sort' => '-7',
      'region' => 'block',
    ),
    'criteria_negative' => array(
      'sort' => '-6',
      'region' => 'block',
    ),
    'custom_paths' => array(
      'sort' => '-5',
      'region' => 'block',
    ),
    'submit_button' => array(
      'sort' => '-4',
      'region' => 'block',
    ),
    'content_types' => array(
      'sort' => '-8',
      'region' => 'block',
    ),
  );
  $export['custom_search_blocks_1_order'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_other';
  $strongarm->value = array(
    'file_entity' => 'file_entity',
    'advanced_help' => 0,
    'apachesolr_search' => 0,
    'user' => 0,
  );
  $export['custom_search_blocks_1_other'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_paths';
  $strongarm->value = 'search/node/[key]|Search';
  $export['custom_search_blocks_1_paths'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_paths_selector';
  $strongarm->value = 'select';
  $export['custom_search_blocks_1_paths_selector'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_paths_selector_label';
  $strongarm->value = 'Customize your search';
  $export['custom_search_blocks_1_paths_selector_label'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_paths_selector_label_visibility';
  $strongarm->value = 0;
  $export['custom_search_blocks_1_paths_selector_label_visibility'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_search_box_region';
  $strongarm->value = 'block';
  $export['custom_search_blocks_1_search_box_region'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_search_box_weight';
  $strongarm->value = '-10';
  $export['custom_search_blocks_1_search_box_weight'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_size';
  $strongarm->value = '27';
  $export['custom_search_blocks_1_size'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_submit_button_region';
  $strongarm->value = 'block';
  $export['custom_search_blocks_1_submit_button_region'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_submit_button_weight';
  $strongarm->value = '-4';
  $export['custom_search_blocks_1_submit_button_weight'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_submit_text';
  $strongarm->value = 'Search';
  $export['custom_search_blocks_1_submit_text'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_text';
  $strongarm->value = '';
  $export['custom_search_blocks_1_text'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_type_selector';
  $strongarm->value = 'checkboxes';
  $export['custom_search_blocks_1_type_selector'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_type_selector_all';
  $strongarm->value = '-Any-';
  $export['custom_search_blocks_1_type_selector_all'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_type_selector_label';
  $strongarm->value = 'Search for';
  $export['custom_search_blocks_1_type_selector_label'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_blocks_1_type_selector_label_visibility';
  $strongarm->value = 0;
  $export['custom_search_blocks_1_type_selector_label_visibility'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'search_api_solr_site_hash';
  $strongarm->value = '53yepm';
  $export['search_api_solr_site_hash'] = $strongarm;

  return $export;
}
